user:
  uri: lb://cseu-user
  id: cseu-user-8080
server:
  port: 8085
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-wait: -1
        max-active: 8
  datasource:
    hikari:
      login-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 20
      connection-timeout: 60000
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/cseu
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        tags: version=1.0,author=yalong.xue
        healthCheckPath: /u/u/actuator/health
        healthCheckInterval: 5s
        ip-address: ${HOST_ADDRESS:localhost}
        port: ${SERVER_PORT:${server.port}}
        instance-id: ${spring.application.name}-${server.port}
        service-name: ${spring.application.name}
    management:
      endpoints:
        web:
          exposure:
            include: '*'
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: ${user.id}
          # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
          uri: ${user.uri}
          predicates:
            # 重点！转发该路径！,/userapi/**,
            - Path=/u/u/**
          #而不是我们期望的去掉userapi，只保留**部分
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                # 需要与上边的方法名保持一致
                rate-limiter: "#{@systemRedisRateLimiter}"
                # 需要与策略类的方法名保持一致。
                key-resolver: "#{@sysKeyResolver}"
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/timeout
#            - Auth=true
    loadbalancer:
      retry:
        enabled: true
  hystrix:
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 3000

  application:
    name: cseu-gateway
  mvc:
    favicon:
      enabled: false
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cseu.server.user.bean
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    # 热加载mapper文件
    refresh: true
logging:
  level:
    com:
      cseu:
        server: info




