spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xueyalong/cseu-config.git
          search-paths: config
          username: xueyl101@163.com
          password: xueyalong0321
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        tags: version=1.0,author=yalong.xue
        healthCheckPath: /config/actuator/health
        healthCheckInterval: 5s
        ip-address: ${HOST_ADDRESS:localhost}
        port: ${SERVER_PORT:${server.port}}
        instance-id: ${spring.application.name}-${server.port}
        service-name: ${spring.application.name}
  datasource:
    hikari:
      login-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 20
      connection-timeout: 60000
#    username: root
#    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/cseu
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.190.119.44:3306/goabroad
    username: zcq
    password: dig.1234
  application:
    name: cseu-config