spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xueyalong/cseu-config.git
          search-paths: config
          username: xueyl101@163.com
          password: xueyalong0321

