spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xueyalong/cseu-config.git
          search-paths: config
          username:
          password:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        tags: version=1.0,author=yalong.xue
        healthCheckPath: /config/actuator/health
        healthCheckInterval: 5s
        ip-address: ${HOST_ADDRESS:localhost}
        port: ${SERVER_PORT:${server.port}}
        instance-id: ${spring.application.name}-${server.port}
        service-name: ${spring.application.name}
  application:
    name: cseu-config